config/routes.rb
Medilines::Application.routes.draw do
  #default_url_options :only_path => true

  mount Ckeditor::Engine => '/ckeditor'

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to                    => 'page#page',
                                  :page => 'home'
  get   '/promotions'         => 'page#promotions',
        as: :promotions,          :page => 'promotions'
  get   '/contacts'           => 'page#contacts',
        as: :contacts,            :page => 'contacts'
  post '/contacts'            => 'page#send_mail',
        as: :send_mail,           :page => 'send_mail'
  get   '/contacts/mail-sent' => 'page#page',
        as: :mail_sent,           :page => 'mail-sent'

  scope '/dental-units', :category => 'dental-units' do
    root :to                           => 'main#category',
          as: :dentals
    get ':brand'                       => 'main#category_brand',
          as: :dental_category_brand
    get ':brand/:product'              => 'main#product',
          as: :dental_category_brand_product
  end

  scope '/visual-systems', :category => 'visual-systems' do
    root :to                           => 'main#category',
          as: :visuals
    get ':subcategory'                 => 'main#subcategory',
          as: :visual_category
    get ':subcategory/:brand'          => 'main#category_brand',
          as: :visual_category_brand
    get ':subcategory/:brand/:product' => 'main#product',
          as: :visual_category_brand_product
  end

  scope '/components', :category => 'components' do
    root :to                           => 'main#category',
          as: :components
    get ':subcategory'                 => 'main#subcategory',
          as: :components_category
    get ':subcategory/:brand'          => 'main#category_brand',
          as: :components_category_brand
    get ':subcategory/:brand/:product' => 'main#product',
          as: :components_category_brand_product
  end

  #scope '/spare-parts', :category => 'spare-parts' do
  #  root :to                              => 'main#category',
  #       as: :spares
  #  get ':subcategory'                 => 'main#subcategory',
  #      as: :spare_category
  #  get ':subcategory/:brand'          => 'main#brand',
  #      as: :spare_category_product
  #  get ':subcategory/:brand/:product' => 'main#product',
  #      as: :spare_category_brand_product
  #end

  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404'
  end
end

app/views/messages/_form.html.haml
= form_tag send_mail_path do
  - if @message.errors.any?
    #error_explanation
      %h2= "Вы допустили ошибки при заполнении формы"
      %ul
        - @message.errors.full_messages.each do |msg|
          %li= msg
  =h negative_captcha(@captcha)
  .field
    = negative_label_tag(@captcha, :name, 'Имя')
    = negative_text_field_tag(@captcha, :name)
  .field
    = negative_label_tag(@captcha, :email, 'Email')
    = negative_text_field_tag(@captcha, :email, :size => "28")
  .field
    = negative_label_tag(@captcha, :content, 'Сообщение')
    = negative_text_area_tag(@captcha, :content, :size => "28x6")

  .actions
    = submit_tag 'Отправить'