config/routes.rb
Medilines::Application.routes.draw do
  #default_url_options :only_path => true

  mount Ckeditor::Engine => '/ckeditor'

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to                    => 'page#page',
                                  :page => 'home'
  get   '/promotions'         => 'page#promotions',
        as: :promotions,          :page => 'promotions'
  get   '/contacts'           => 'page#contacts',
        as: :contacts,            :page => 'contacts'
  post '/contacts'            => 'page#send_mail',
        as: :send_mail,           :page => 'send_mail'
  get   '/contacts/mail-sent' => 'page#page',
        as: :mail_sent,           :page => 'mail-sent'

  scope '/dental-units', :category => 'dental-units' do
    root :to                           => 'main#category',
          as: :dentals
    get ':brand'                       => 'main#category_brand',
          as: :dental_category_brand
    get ':brand/:product'              => 'main#product',
          as: :dental_category_brand_product
  end

  scope '/visual-systems', :category => 'visual-systems' do
    root :to                           => 'main#category',
          as: :visuals
    get ':subcategory'                 => 'main#subcategory',
          as: :visual_category
    get ':subcategory/:brand'          => 'main#category_brand',
          as: :visual_category_brand
    get ':subcategory/:brand/:product' => 'main#product',
          as: :visual_category_brand_product
  end

  scope '/components', :category => 'components' do
    root :to                           => 'main#category',
          as: :components
    get ':subcategory'                 => 'main#subcategory',
          as: :components_category
    get ':subcategory/:brand'          => 'main#category_brand',
          as: :components_category_brand
    get ':subcategory/:brand/:product' => 'main#product',
          as: :components_category_brand_product
  end

  #scope '/spare-parts', :category => 'spare-parts' do
  #  root :to                              => 'main#category',
  #       as: :spares
  #  get ':subcategory'                 => 'main#subcategory',
  #      as: :spare_category
  #  get ':subcategory/:brand'          => 'main#brand',
  #      as: :spare_category_product
  #  get ':subcategory/:brand/:product' => 'main#product',
  #      as: :spare_category_brand_product
  #end

  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404'
  end
end

app/views/pages/contacts.html.haml
%h1 Контакты

.contact-details{ itemscope: true, itemtype: "http://schema.org/Organization" }
  %address.full-contacts
    -#= @page.content.html_safe
    %h3 Приходите по адресу:

    %p{ itemscope: true, itemprop: "address",
        itemtype: "http://schema.org/PostalAddress" }
      %span{ itemprop: "addressLocality" } Санкт-Петербург
      %span{ itemprop: "streetAddress" } ул. Коллонтай, д. 41<br />лит. Д, оф. 205

    %h3 Звоните:

    %p{ itemprop: "telephone" } (812) 983-49-96

    %p{ itemprop: "telephone" } 8 921 375-74-61

    %p{ itemprop: "telephone" } 8 905 287-72-47

    %h3 Пишите нам:

    %p{ itemprop: "email" }
      = link_to "info@medilines.ru", "mailto:info@medilines.ru"


  .contact-form
    %h3 Свяжитесь с нами
    = render '/messages/form'

#ya-map

:javascript
  ymaps.ready(initYMap);

app/views/pages/home.html.haml
%nav#service-menu
  %ul.nav
    %li
      = link_to image_tag("r_dentalset.jpg", :size => "", :alt => "Стоматологиеское кресло"), dentals_path
      %h2= link_to 'Стоматологические установки', dentals_path
      %dl
        %dt= link_to 'Forest', dental_category_brand_path(:forest)
        %dd США
        %dt= link_to 'Fedesa', dental_category_brand_path(:fedesa)
        %dd Испания
    
    %li
      = link_to image_tag("r_rentgen.jpg", :size => "", :alt => "Стоматологиеское кресло"), visuals_path
      %h2= link_to 'Рентген, лазеры, системы визуализации', visuals_path
      %p В Медилайн Сервис можно купить стоматологическую установку, рентген, лазер, системы визуализации, комплектующие стоматологического кабинета.
      
    %li
      = link_to image_tag("r_components.jpg", :size => "", :alt => "Стоматологиеское кресло"), components_path
      %h2= link_to 'Комплектующие стоматологического кабинета', components_path

    %li
      -#= link_to image_tag("r_rentgen.jpg", :size => "", :alt => "Стоматологиеское кресло"), root_path
      = image_tag "r_spares.jpg", :size => "", :alt => "Стоматологиеское кресло"
      %h2 Запасные части
      
      
      

app/views/pages/mail-sent.html.haml
- if @error
  %h1 Ошибка отправки сообщения
  %p Извините, произошла ошибка во время отправки сообщения. Попробуйте еще
  раз или напишите нам на почту <a href="mailto:info@medilines
  .ru">info@medilines.ru</a>

- else
  = @page.content.html_safe

app/views/pages/promotions.html.haml
%h1 Акции

= @page.intro.html_safe

- @promotions.each do |promo|
  .promotion
    %h2= promo.title
    .details= promo.content.html_safe