config/routes.rb
Medilines::Application.routes.draw do
  #default_url_options :only_path => true

  mount Ckeditor::Engine => '/ckeditor'

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to                    => 'page#page',
                                  :page => 'home'
  get   '/promotions'         => 'page#promotions',
        as: :promotions,          :page => 'promotions'
  get   '/contacts'           => 'page#contacts',
        as: :contacts,            :page => 'contacts'
  post '/contacts'            => 'page#send_mail',
        as: :send_mail,           :page => 'send_mail'
  get   '/contacts/mail-sent' => 'page#page',
        as: :mail_sent,           :page => 'mail-sent'

  scope '/dental-units', :category => 'dental-units' do
    root :to                           => 'main#category',
          as: :dentals
    get ':brand'                       => 'main#category_brand',
          as: :dental_category_brand
    get ':brand/:product'              => 'main#product',
          as: :dental_category_brand_product
  end

  scope '/visual-systems', :category => 'visual-systems' do
    root :to                           => 'main#category',
          as: :visuals
    get ':subcategory'                 => 'main#subcategory',
          as: :visual_category
    get ':subcategory/:brand'          => 'main#category_brand',
          as: :visual_category_brand
    get ':subcategory/:brand/:product' => 'main#product',
          as: :visual_category_brand_product
  end

  scope '/components', :category => 'components' do
    root :to                           => 'main#category',
          as: :components
    get ':subcategory'                 => 'main#subcategory',
          as: :components_category
    get ':subcategory/:brand'          => 'main#category_brand',
          as: :components_category_brand
    get ':subcategory/:brand/:product' => 'main#product',
          as: :components_category_brand_product
  end

  #scope '/spare-parts', :category => 'spare-parts' do
  #  root :to                              => 'main#category',
  #       as: :spares
  #  get ':subcategory'                 => 'main#subcategory',
  #      as: :spare_category
  #  get ':subcategory/:brand'          => 'main#brand',
  #      as: :spare_category_product
  #  get ':subcategory/:brand/:product' => 'main#product',
  #      as: :spare_category_brand_product
  #end

  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404'
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, :use => :slugged

  belongs_to :parent, :class_name => 'Category', :foreign_key => 'parent_id'
  has_many :products
  has_many :brands, :through => :products, :uniq => true

  attr_accessible :description, :name, :slug, :parent, :logo, :parent_id

  validates_presence_of :name, :slug
  validates_uniqueness_of :name, :slug
  validates_length_of :name, :minimum => 4

  mount_uploader :logo, CategoryImageUploader

  scope :roots,      where("parent_id IS NULL")
  scope :join_parent, lambda { |slug|
    joins("JOIN categories AS cat2 ON categories.parent_id = cat2.id").
    where("cat2.slug = ?", slug)
  }
  scope :dentals,    join_parent('dental-units')
  scope :visuals,    join_parent('visual-systems')
  scope :components, join_parent('components')
  scope :spares,     join_parent('spare-parts')

  def title
    name
  end

  def intro
    description
  end

  def children
    Category.includes(:brands).find_all_by_parent_id id
  end

  def root?
    parent_id.nil?
  end

  def should_generate_new_friendly_id?
    new_record?
  end
end

app/views/categories/brands.html.haml
- @brands.each do |brand|
  %div{class: "brand #{brand.slug}"}
    = image_tag(brand.image_url, :size => '157x153',
      :alt => "#{@category.name} - #{brand.name}")

    .brand-description
      %h2= link_to brand.name, brand_url(brand, @category)
      = image_tag(brand.flag_url, :alt => "Флаг #{brand.country}")
      = brand.country
      %p= short_text(brand.description, 150)

    .details
      -if not brand.details.empty?
        = short_text(brand.details.html_safe, 300)
      - else
        - brand.products.each do |product|
          .product
            = link_to image_tag(product.image_url(:thumb),
              :alt => "Товар #{brand.name}"), product_url(product)
            %span= link_to product.name, product_url(product)

app/views/categories/category_dental-units.html.haml
- @brands.each do |brand|
  %div{class: "brand #{brand.slug}"}
    = image_tag(brand.image_url, :alt => "Cтоматологическое кресло #{brand.name}")

    .brand-description
      %h2= link_to brand.name, dental_brand_path(brand)
      = image_tag(brand.flag_url, :alt => "Флаг #{brand.country}")
      = brand.country
      %p= brand.description

    .details
      = brand.details.html_safe

app/views/categories/category_dentals.html.haml
.brand.forest
  = image_tag("forest-brand.jpg", :size => "150x153", :alt => "Cтоматологическое кресло Forest")
  .brand-description
    %h2 Forest Dental
    = image_tag("us.png", :size => "16x16", :alt => "Флаг США")
    США
    %p Форест является одним из передовых производителей в Северной Америке. Современные технологии в роскошном дизайне за разумную цену.
  .details
    %h4 48 вариантов!
    %p Получите установку вашей мечты, выбрав из:
    %ul
      %li 3-х модулей врача
      %li 3-х модулей ассистента
      %li 2-х ламп

.brand.fedesa
  = image_tag("fedesa-brand.jpg", :size => "157x152", :alt => "Cтоматологическое кресло Fedesa")
  .brand-description
    %h2 Fedesa
    = image_tag("es.png", :size => "16x11", :alt => "Флаг Испании")
    = image_tag("ch-flag.png", :size => "16x11", :alt => "Флаг Швейцарии")
    Испания — Швейцария
    %p Федеса является одним из наиболее прогрессивных производителей в Испании. Европейский лидер продаж.
  .details
    %h4 7 моделей
    %ul
      %li Coral Air - экономичная функциональность
      %li Midway (Air) - экономичная функциональность
      %li Coral Lux - экономичная функциональность
      %li Astral - экономичная функциональность
      %li Astro - экономичная функциональность
      %li Carisma - экономичная функциональность

app/views/categories/category_with_brands.html.haml
- @brands.each do |brand|
  %div{class: "brand #{brand.slug}"}
    = image_tag(brand.image_url, :alt => "#{@category.name} - #{brand.name}")

    .brand-description
      %h2= link_to brand.name, brand_url(brand, @category)
      = image_tag(brand.flag_url, :alt => "Флаг #{brand.country}")
      = brand.country
      %p= brand.description

    .details
      = brand.details.html_safe

app/views/categories/category_with_categories.html.haml
- @subcategories.each do |cat|
  %div{class: "category #{cat.slug}"}
    = image_tag(cat.logo_url, :alt => "Категория #{cat.name}") if cat.logo

    .cat-description
      %h2= link_to cat.name, url_for([root_cat(params[:category]), cat])

    .details
      %p= cat.description.html_safe if cat.description

app/views/categories/index.html.haml
- @category.children.each do |cat|

  %div{class: "category #{cat.slug}"}
    = link_to image_tag(cat.logo_url(:small), :alt => "Категория #{cat.name}"),
      subcategory_url(cat)

    .details
      %h3= link_to cat.name, subcategory_url(cat)
      .info= cat.description.html_safe if cat.description

    .brands
      - cat.brands.each do |brand|
        .brand
          = link_to image_tag(brand.logo_url(:small),
            :alt => "Бренд #{brand.name}"), brand_url(brand, cat)
          %span= link_to brand.name, brand_url(brand, cat)