config/routes.rb
Medilines::Application.routes.draw do
  #default_url_options :only_path => true

  mount Ckeditor::Engine => '/ckeditor'

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to                    => 'page#page',
                                  :page => 'home'
  get   '/promotions'         => 'page#promotions',
        as: :promotions,          :page => 'promotions'
  get   '/contacts'           => 'page#contacts',
        as: :contacts,            :page => 'contacts'
  post '/contacts'            => 'page#send_mail',
        as: :send_mail,           :page => 'send_mail'
  get   '/contacts/mail-sent' => 'page#page',
        as: :mail_sent,           :page => 'mail-sent'

  scope '/dental-units', :category => 'dental-units' do
    root :to                           => 'main#category',
          as: :dentals
    get ':brand'                       => 'main#category_brand',
          as: :dental_category_brand
    get ':brand/:product'              => 'main#product',
          as: :dental_category_brand_product
  end

  scope '/visual-systems', :category => 'visual-systems' do
    root :to                           => 'main#category',
          as: :visuals
    get ':subcategory'                 => 'main#subcategory',
          as: :visual_category
    get ':subcategory/:brand'          => 'main#category_brand',
          as: :visual_category_brand
    get ':subcategory/:brand/:product' => 'main#product',
          as: :visual_category_brand_product
  end

  scope '/components', :category => 'components' do
    root :to                           => 'main#category',
          as: :components
    get ':subcategory'                 => 'main#subcategory',
          as: :components_category
    get ':subcategory/:brand'          => 'main#category_brand',
          as: :components_category_brand
    get ':subcategory/:brand/:product' => 'main#product',
          as: :components_category_brand_product
  end

  #scope '/spare-parts', :category => 'spare-parts' do
  #  root :to                              => 'main#category',
  #       as: :spares
  #  get ':subcategory'                 => 'main#subcategory',
  #      as: :spare_category
  #  get ':subcategory/:brand'          => 'main#brand',
  #      as: :spare_category_product
  #  get ':subcategory/:brand/:product' => 'main#product',
  #      as: :spare_category_brand_product
  #end

  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404'
  end
end

app/views/layouts/_breadcrumbs.html.haml
- breadcrumbs = get_breadcrumbs
- if breadcrumbs.any?
  %nav
    %ul.nav.breadcrumbs
      - breadcrumbs.each do |link|
        %li= link.html_safe

app/views/layouts/_footer.html.haml
%address.address
  %p.address Санкт-Петербург, ул. Коллонтай, д. 41 лит. Д, оф. 205
  %ul.tel
    %li
      %strong (812) 983-49-96,
    %li 8 921 375-74-61,
    %li 8 921 375-74-61,
    %li (812) 587-97-05 - факс

%address.details
  %p © 2011, ООО «Медилайн Сервис»
  %p= link_to 'Веб-разработка', 'http://riabit.ru', class: 'riabit'

app/views/layouts/_header.html.haml
= link_to image_tag("logo.png", :size => "277x56", :alt => "Медилиайн Сервис"), root_path

%address.contacts
  .main
    %p.tel (812) 983-49-96
    %p.email= mail_to 'info@medilines.ru'
  .alternative
    %p.tel 8 921 375-74-61
    %p.tel 8 905 287-72-47

%nav#main-menu
  %ul.nav
    = nav_item 'Установки',       dentals_path
    = nav_item 'Визуализация',    visuals_path
    = nav_item 'Комплектующие',   components_path
    = nav_item 'Запчасти',        'spares_path',      true
    = nav_item 'Акции',           promotions_path
    = nav_item 'Скачать каталог', '/docs/MediLines_Catalog_2013.pdf'
    = nav_item 'Контакты',        contacts_path

app/views/layouts/application.html.haml
!!!
%html{lang: 'ru'}
  %head
    %meta{ charset: 'utf-8' }/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= page_title(@page)
    %meta{ name: 'description', content: @page.description }/
    %meta{ name: 'keywords', content: @page.keywords }/
    = favicon_link_tag 'favicon.ico'
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    / = javascript_include_tag "//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"
    = javascript_include_tag "//api-maps.yandex.ru/2.0-stable/?load=package.standard,package.traffic&lang=ru-RU&"
    = csrf_meta_tags
    /[if lt IE 9]
      %script{ :src => '//html5shiv.googlecode.com/svn/trunk/html5.js' }

  %body{:class => "#{controller_name} #{action_name}"}
    %header
      .container
        = render 'layouts/header'

    - unless @page.intro.blank?
      %section.intro
        .container
          = @page.intro.html_safe

    %section#main
      .container
        -#%p.notice= notice
        -#%p.alert= alert
        = render 'layouts/breadcrumbs'


        = yield


    %footer
      .container
        = render 'layouts/footer'

    = render 'layouts/analytics'